// DemoVue/src/Contador.vue
<template>
  <div>
    <h2>Contador: {{ contador }}</h2>
    <button @click="incrementar">Incrementar</button>
    <button @click="decrementar">Decrementar</button>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const contador = ref(0)

const incrementar = () => {
  contador.value++
}

const decrementar = () => {
  contador.value--
}
</script>

// Demo_React/DemoHook/src/Contador.jsx
import { useState } from "react";

export default function contador(){
    const [contador, setContador]=useState(0);
    
    return(
        <div>
            <h2>{contador}</h2>
            <button onClick={()=>setContador(contador+1)}>Incrementar</button>
            <button onClick={()=>setContador(contador-1)}>Decrementar</button>
            <button onClick={()=>setContador(0)}>Reiniciar</button>
        </div>
    );
}
